// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ApplicationRecord is the golang structure of table applicationRecord for DAO operations like Where/Data.
type ApplicationRecord struct {
	g.Meta       `orm:"table:applicationRecord, do:true"`
	Id           interface{} // 申请记录ID
	CreateTime   *gtime.Time // 创建时间
	UpdateTime   *gtime.Time // 更新时间
	DeleteTime   *gtime.Time // 删除时间
	UserId       interface{} // 用户ID
	ResourceType interface{} // 资源类型 1:chainTemplate
	ResourceId   interface{} // 资源id
	Operation    interface{} // 操作类型 1:下架
	Reason       interface{} // 申请原因
	Status       interface{} // 申请状态 1:未处理 2:已通过 3:已驳回
}
