// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Bot is the golang structure of table bot for DAO operations like Where/Data.
type Bot struct {
	g.Meta        `orm:"table:bot, do:true"`
	Id            interface{} // 机器人ID
	CreateTime    *gtime.Time // 创建时间
	UpdateTime    *gtime.Time // 更新时间
	DeleteTime    *gtime.Time // 删除时间
	Name          interface{} // 机器人名称
	ChainId interface{} // 流程ID
	UserType      interface{} // 用户类型
	UserId        interface{} // 用户Id
	Uuid          interface{} //
	PromptType    interface{} // 1:提示词 2:提示词工程 3:提示词流程图
	ScenarioId    interface{} // 场景id
	IsPublic      interface{} // 是否是公开，1代表true ，0 代表false
}
