// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BotFolder is the golang structure of table botFolder for DAO operations like Where/Data.
type BotFolder struct {
	g.Meta            `orm:"table:botFolder, do:true"`
	Id                interface{} //
	CreateTime        *gtime.Time // 创建时间
	UpdateTime        *gtime.Time // 更新时间
	DeleteTime        *gtime.Time // 删除时间
	BotId             interface{} // 机器人ID
	FolderId interface{} // 文件夹ID
}
