// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BotUserFile is the golang structure of table botUserFile for DAO operations like Where/Data.
type BotUserFile struct {
	g.Meta     `orm:"table:botUserFile, do:true"`
	Id         interface{} // 流程ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	BotId      interface{} // 机器人ID
	FileId     interface{} // 文件ID
}
