// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplateScene is the golang structure of table chainTemplateScene for DAO operations like Where/Data.
type ChainTemplateScene struct {
	g.Meta          `orm:"table:chainTemplateScene, do:true"`
	Id              interface{} // ID
	CreateTime      *gtime.Time // 创建时间
	UpdateTime      *gtime.Time // 更新时间
	DeleteTime      *gtime.Time // 删除时间
	ChainTemplateId interface{} // chainID
	SceneId         interface{} // 场景id
}
