// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BotUserFile is the golang structure of table botUserFile for DAO operations like Where/Data.
type chainBotUserRelation struct {
	g.Meta     `orm:"table:chain_bot_user_relation, do:true"`
	Id         interface{} // 流程ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	relationId interface{} // 关系ID
	relationType interface{} // 关系类型
	userPermission interface{} // 用户权限
	userId interface{} // 用户ID
}
