// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplate is the golang structure of table chainTemplate for DAO operations like Where/Data.
type ChainTemplate struct {
	g.Meta              `orm:"table:chainTemplate, do:true"`
	Id                  interface{} // 模版ID
	CreateTime          *gtime.Time // 创建时间
	UpdateTime          *gtime.Time // 更新时间
	DeleteTime          *gtime.Time // 删除时间
	UserId              interface{} // 用户ID
	ChainTemplateName   interface{} // 模版名称
	Nodes               interface{} // 节点数据
	Edges               interface{} // 边缘数据
	FatherId            interface{} // 父ID
	Version             interface{} // 版本号
	VersionDesc         interface{} // 版本描述
	Desc                interface{} // 描述
	Icon                interface{} // icon图
	ChainLevel          interface{} // 层级
	ApproveStatus       interface{} // 审批状态  1：待审批 2:已通过 3:已驳回
	ChainTemplateStatus interface{} // 上架下架状态 1：上架 2:下架
	BotId               interface{} // 如果当前版本上架，则对应当前版本的sysbot的id
	UseKnowledge        interface{} // 是否使用知识库
}
