// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplateInfo is the golang structure of table chainTemplateInfo for DAO operations like Where/Data.
type ChainTemplateInfo struct {
	g.Meta                  `orm:"table:chainTemplateInfo, do:true"`
	Id                      interface{} // 模版ID
	CreateTime              *gtime.Time // 创建时间
	UpdateTime              *gtime.Time // 更新时间
	DeleteTime              *gtime.Time // 删除时间
	UserId                  interface{} // 用户ID
	ChainTemplateName       interface{} // 模版名称
	FatherId                interface{} // 父ID
	Version                 interface{} // 版本号
	VersionDesc             interface{} // 版本描述
	Desc                    interface{} // 描述
	Icon                    interface{} // icon图
	DownloadCount           interface{} // 下载次数
	ChainLevel              interface{} // 层级
	ChainTemplateInfoStatus interface{} // 上架下架状态 1：上架 2:下架
	BotId                   interface{} // 如果当前版本上架，则对应当前版本的sysbot的id
	TemplateId              interface{} // 关联的模版id
}
