// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Chain is the golang structure of table chain for DAO operations like Where/Data.
type Chain struct {
	g.Meta              `orm:"table:chain, do:true"`
	Id                  interface{} // 流程ID
	CreateTime          *gtime.Time // 创建时间
	UpdateTime          *gtime.Time // 更新时间
	DeleteTime          *gtime.Time // 删除时间
	UserId              interface{} // 用户ID
	ChainName           interface{} // 流程名称
	Nodes               interface{} // 节点数据
	Edges               interface{} // 边缘数据
	UserType            interface{} // 用户类型
	UseKnowledge        interface{} // 是否使用知识库
	ChainLevel          interface{} // 层级
	FatherId            interface{} // 父ID，记录所属模版
	FatherTemplateId    interface{} // 记录所属具体某个vesion的模版
	IsUpload            interface{} // 0 没上传 1 已上传
	ChainTemplateId     interface{} // 上传后的模版ID
	IsInMarket          interface{} // 是否已上架 0:未上架 1:已上架
	ChainTemplateInfoId interface{} // 上架后的模版ID
}
