// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Chat is the golang structure of table chat for DAO operations like Where/Data.
type Chat struct {
	g.Meta     `orm:"table:chat, do:true"`
	Id         interface{} // 聊天ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	Name       interface{} // 对话名称
	Type       interface{} // 对话类型
	UserId     interface{} // 用户ID
	ContextType interface{} // 上下文类型
}
