// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompareRecord is the golang structure of table compareRecord for DAO operations like Where/Data.
type CompareRecord struct {
	g.Meta          `orm:"table:compareRecord, do:true"`
	Id              interface{} // 记录ID
	CreateTime      *gtime.Time // 创建时间
	UpdateTime      *gtime.Time // 更新时间
	DeleteTime      *gtime.Time // 删除时间
	ParentId        interface{} // 父记录ID
	SourceMessageId interface{} // 源消息ID
	TargetMessageId interface{} // 目标消息ID
	Result          interface{} // 比较结果
}
