// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FolderDataSet is the golang structure of table FolderDataSet for DAO operations like Where/Data.
type FolderDataSet struct {
	g.Meta     `orm:"table:folder_data_set, do:true"`
	Id         interface{} // 主键
	CreateTime 	*gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	SetFolderId       interface{} // 文件夹Id
	DataSetId interface{} // 数据集Id

}
