// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Chat is the golang structure of table chat for DAO operations like Where/Data.
type MemberToken struct {
	g.Meta     `orm:"table:memberToken, do:true"`
	Id         interface{} // 聊天ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	UserId   interface{} // 用户ID
	TokenTotal interface{} // token总数
	TokenUse interface{} // token使用数
}
