// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Message is the golang structure of table message for DAO operations like Where/Data.
type Message struct {
	g.Meta      `orm:"table:message, do:true"`
	Id          interface{} // 消息ID
	CreateTime  *gtime.Time // 创建时间
	UpdateTime  *gtime.Time // 更新时间
	DeleteTime  *gtime.Time // 删除时间
	UserId      interface{} // 用户ID
	Type        interface{} // 消息发送者类型
	Content     interface{} // 消息内容
	ContentType interface{} // 消息内容类型
	ParentId    interface{} // 父消息ID
	Mark        interface{} // 标记
	Feedback    interface{} // 反馈信息
	Active      interface{} // 是否有效
	ChatId      interface{} // 所属对话id
	BotId 	interface{} // 机器人Id
}
