// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Model is the golang structure of table model for DAO operations like Where/Data.
type Model struct {
	g.Meta     `orm:"table:model, do:true"`
	Id         interface{} // 模型ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	Name       interface{} // 模型名称
	Desc       interface{} // 模型描述
	SortOrder  interface{} // 排序
	MaxTokenLimit interface{} // 最大token限制
	Tag  	interface{} // 标签
	Factor 	interface{} // 因子
}
