// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table order for DAO operations like Where/Data.
type Order struct {
	g.Meta               `orm:"table:order, do:true"`
	Id                   interface{} // 订单ID
	CreateTime           *gtime.Time // 创建时间
	UpdateTime           *gtime.Time // 更新时间
	DeleteTime           *gtime.Time // 删除时间
	UserId               interface{} // 用户ID
	OrderNumber          interface{} // 订单号
	ProductId            interface{} // 商品ID
	ProductName          interface{} // 商品名称
	ProductDescription   interface{} // 商品描述
	Amount               interface{} // 商品数量
	ProductPrice         interface{} // 商品单价
	ProductOriginalPrice interface{} // 商品原价
	Status               interface{} // 订单状态
	PaymentTime          *gtime.Time // 支付时间
}
