// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Payment is the golang structure of table payment for DAO operations like Where/Data.
type Payment struct {
	g.Meta        `orm:"table:payment, do:true"`
	Id            interface{} // 支付记录ID
	CreateTime    *gtime.Time // 创建时间
	UpdateTime    *gtime.Time // 更新时间
	DeleteTime    *gtime.Time // 删除时间
	MethodType    interface{} // 支付方式
	Amount        interface{} // 支付金额
	Status        interface{} // 支付状态
	PaymentTime   *gtime.Time // 付款时间
	OrderId       interface{} // 订单ID
	TransactionId interface{} // 交易号
}
