// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table product for DAO operations like Where/Data.
type Product struct {
	g.Meta        `orm:"table:product, do:true"`
	Id            interface{} // 商品ID
	CreateTime    *gtime.Time // 创建时间
	UpdateTime    *gtime.Time // 更新时间
	DeleteTime    *gtime.Time // 删除时间
	Name          interface{} // 商品名称
	Description   interface{} // 商品描述
	Price         interface{} // 商品价格
	Duration      interface{} // 使用时长（单位：豪秒）
	Status        interface{} // 商品状态
	OriginalPrice interface{} // 原价
}
