// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table product for DAO operations like Where/Data.
type PromptChainLog struct {
	g.Meta        `orm:"table:promptChainLog, do:true"`
	Id            interface{} // 商品ID
	CreateTime    *gtime.Time // 创建时间
	UpdateTime    *gtime.Time // 更新时间
	TraceId	   	  interface{} // 
	Uuid  		  interface{} // 
	ExecutionTime interface{} //
	TokenConsumed interface{} //
	Results 		  interface{} //
	ChainId 	  interface{} //
	MessageId 	  interface{} //

}
