// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure of table file for DAO operations like Where/Data.
type File struct {
	g.Meta       `orm:"table:file, do:true"`
	Id           interface{} //
	CreateTime   *gtime.Time // 创建时间
	UpdateTime   *gtime.Time // 更新时间
	DeleteTime   *gtime.Time // 删除时间
	Url          interface{} // 文件地址
	Name         interface{} // 文件名
	ParseStatus  interface{} // 解析状态 1：Parsing  2:Success 3:Failure
	Md5          interface{} // 文件的md5值
	Size         interface{} // 文件大小，单位kb
}
