// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FolderFile is the golang structure of table folderFile for DAO operations like Where/Data.
type FolderFile struct {
	g.Meta            `orm:"table:folderFile, do:true"`
	Id                interface{} //
	CreateTime        *gtime.Time // 创建时间
	UpdateTime        *gtime.Time // 更新时间
	DeleteTime        *gtime.Time // 删除时间
	FolderId interface{} // 文件夹ID
	FileId    interface{} // 资源文件ID
}
