// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Scene is the golang structure of table scene for DAO operations like Where/Data.
type Scene struct {
	g.Meta     `orm:"table:scene, do:true"`
	Id         interface{} // 记录ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	SceneName  interface{} // 场景名
}
