// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SetFolder is the golang structure of table SetFolder for DAO operations like Where/Data.
type SetFolder struct {
	g.Meta     `orm:"table:set_folder, do:true"`
	Id         interface{} // 主键
	CreateTime 	*gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	SetFolderName       interface{} // 文件夹名称
	UserId interface{} // 用户ID
	EmbeddingModel interface{} // 嵌入模型

}
