// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Setting is the golang structure of table setting for DAO operations like Where/Data.
type Setting struct {
	g.Meta     `orm:"table:setting, do:true"`
	Id         interface{} // 主键
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	ServiceType       interface{} // 服务类型
	Value       interface{} // 值
	ChainId interface{} // 链id
	BotId interface{} // 机器人id
}
