// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SettingConfig is the golang structure of table settingConfig for DAO operations like Where/Data.
type SettingConfig struct {
	g.Meta     `orm:"table:settingConfig, do:true"`
	Id         interface{} // 主键
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	Name 	 interface{} // 名称
	Desc 	 interface{} // 描述
	Unique 	 interface{} // 唯一标识
	Configs 	 interface{} // 配置

}
