// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure of table SysConfig for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta     `orm:"table:sys_config, do:true"`
	Id         interface{} // 主键
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	Config_key 	 interface{} // 唯一标识
	Config_name 	 interface{} // 名称
	Config_value 	 interface{} // 配置
	Config_type 	 interface{} // 类型
	Remark 	 interface{} // 备注
}
