// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// tokenUsageLimit is the golang structure of table tokenUsageLimit for DAO operations like Where/Data.
type tokenUsageLimit struct {
	g.Meta     `orm:"table:tokenUsageLimit, do:true"`
	Id         interface{} // 模型ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	UserId     interface{} // 用户ID
	ModelId    interface{} // 模型ID
	DailTokens interface{} // Token
}
