// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserApplication is the golang structure of table UserApplication for DAO operations like Where/Data.
type UserApplication struct {
	g.Meta     `orm:"table:userApplication, do:true"`
	Id         interface{} // 主键
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	EnterpriseName string // 企业名称
	Post string // 职位
	Purpose string // 用途
	RequirementScenario string // 需求场景
	Status string // 申请状态 申请成功 申请中
	UserId uint // 用户id
	UserName string // 姓名
	Phone string // 手机号
}
