// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} // 用户ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	DeleteTime *gtime.Time // 删除时间
	Name       interface{} // 用户名
	Phone      interface{} // 手机号码
	Password   interface{} // 密码
	Email      interface{} // 邮箱
	Salt       interface{} // 密码盐值
	Is_admin   interface{} // 是否是管理员
	User_status interface{} // 用户状态
	Is_membership interface{} // 是否是会员
	Member_deadline *gtime.Time // 会员到期时间
	GoogleId  interface{} // 谷歌ID
}
