// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// VerificationCodeDao is the data access object for table verificationCode.
type VerificationCodeDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns VerificationCodeColumns // columns contains all the column names of Table for convenient usage.
}

// VerificationCodeColumns defines and stores column names for table verificationCode.
type VerificationCodeColumns struct {
	Id         string // 验证码ID
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	DeleteTime string // 更新时间
	Phone      string // 手机号码
	Code       string // 验证码
	ExpireTime string // 过期时间
	IsVerified string // 是否已验证
}

// verificationCodeColumns holds the columns for table verificationCode.
var verificationCodeColumns = VerificationCodeColumns{
	Id:         "id",
	CreateTime: "createTime",
	UpdateTime: "updateTime",
	DeleteTime: "deleteTime",
	Phone:      "phone",
	Code:       "code",
	ExpireTime: "expireTime",
	IsVerified: "isVerified",
}

// NewVerificationCodeDao creates and returns a new DAO object for table data access.
func NewVerificationCodeDao() *VerificationCodeDao {
	return &VerificationCodeDao{
		group:   "default",
		table:   "verificationCode",
		columns: verificationCodeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *VerificationCodeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *VerificationCodeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *VerificationCodeDao) Columns() VerificationCodeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *VerificationCodeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *VerificationCodeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *VerificationCodeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
