// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalApproveRecordDao is internal type for wrapping internal DAO implements.
type internalApproveRecordDao = *internal.ApproveRecordDao

// approveRecordDao is the data access object for table approveRecord.
// You can define custom methods on it to extend its functionality as you wish.
type approveRecordDao struct {
	internalApproveRecordDao
}

var (
	// ApproveRecord is globally public accessible object for table approveRecord operations.
	ApproveRecord = approveRecordDao{
		internal.NewApproveRecordDao(),
	}
)

// Fill with you ideas below.
