// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalBotResourceLibraryDao is internal type for wrapping internal DAO implements.
type internalBotResourceLibraryDao = *internal.BotResourceLibraryDao

// botResourceLibraryDao is the data access object for table botFolder.
// You can define custom methods on it to extend its functionality as you wish.
type botResourceLibraryDao struct {
	internalBotResourceLibraryDao
}

var (
	// BotFolder is globally public accessible object for table botFolder operations.
	BotFolder = botResourceLibraryDao{
		internal.NewBotResourceLibraryDao(),
	}
)

// Fill with you ideas below.
