// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalChainDao is internal type for wrapping internal DAO implements.
type internalChainDao = *internal.ChainDao

// chainDao is the data access object for table chain.
// You can define custom methods on it to extend its functionality as you wish.
type chainDao struct {
	internalChainDao
}

var (
	// Chain is globally public accessible object for table chain operations.
	Chain = chainDao{
		internal.NewChainDao(),
	}
)

// Fill with you ideas below.
