// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalCompareRecordDao is internal type for wrapping internal DAO implements.
type internalCompareRecordDao = *internal.CompareRecordDao

// compareRecordDao is the data access object for table compareRecord.
// You can define custom methods on it to extend its functionality as you wish.
type compareRecordDao struct {
	internalCompareRecordDao
}

var (
	// CompareRecord is globally public accessible object for table compareRecord operations.
	CompareRecord = compareRecordDao{
		internal.NewCompareRecordDao(),
	}
)

// Fill with you ideas below.
