// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalResourceFileDao is internal type for wrapping internal DAO implements.
type internalResourceFileDao = *internal.ResourceFileDao

// resourceFileDao is the data access object for table file.
// You can define custom methods on it to extend its functionality as you wish.
type resourceFileDao struct {
	internalResourceFileDao
}

var (
	// File is globally public accessible object for table file operations.
	File = resourceFileDao{
		internal.NewResourceFileDao(),
	}
)

// Fill with you ideas below.
