// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalResourceLibraryFileDao is internal type for wrapping internal DAO implements.
type internalResourceLibraryFileDao = *internal.ResourceLibraryFileDao

// resourceLibraryFileDao is the data access object for table folderFile.
// You can define custom methods on it to extend its functionality as you wish.
type resourceLibraryFileDao struct {
	internalResourceLibraryFileDao
}

var (
	// FolderFile is globally public accessible object for table folderFile operations.
	FolderFile = resourceLibraryFileDao{
		internal.NewResourceLibraryFileDao(),
	}
)

// Fill with you ideas below.
