// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"llmfarm/internal/dao/internal"
)

// internalVerificationCodeDao is internal type for wrapping internal DAO implements.
type internalVerificationCodeDao = *internal.VerificationCodeDao

// verificationCodeDao is the data access object for table verificationCode.
// You can define custom methods on it to extend its functionality as you wish.
type verificationCodeDao struct {
	internalVerificationCodeDao
}

var (
	// VerificationCode is globally public accessible object for table verificationCode operations.
	VerificationCode = verificationCodeDao{
		internal.NewVerificationCodeDao(),
	}
)

// Fill with you ideas below.
