// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ApplicationRecord is the golang structure for table applicationRecord.
type ApplicationRecord struct {
	Id           uint        `json:"id"           ` // 申请记录ID
	CreateTime   *gtime.Time `json:"createTime"   ` // 创建时间
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 更新时间
	DeleteTime   *gtime.Time `json:"deleteTime"   ` // 删除时间
	UserId       int         `json:"userId"       ` // 用户ID
	ResourceType string      `json:"resourceType" ` // 资源类型 1:chainTemplate
	ResourceId   int         `json:"resourceId"   ` // 资源id
	Operation    string      `json:"operation"    ` // 操作类型 1:下架
	Reason       string      `json:"reason"       ` // 申请原因
	Status       string      `json:"status"       ` // 申请状态 1:未处理 2:已通过 3:已驳回
}
