// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ApproveRecord is the golang structure for table approveRecord.
type ApproveRecord struct {
	Id         uint        `json:"id"         ` // 记录ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 删除时间
	UserId     int         `json:"userId"     ` // 用户ID
	TemplateId int         `json:"templateId" ` // 关联的模版id
	Approver   int         `json:"approver"   ` // 审批人id
	Result     string      `json:"result"     ` // 审批结果 1:通过 2:驳回 3:已上架 4:已下架
	Content    string      `json:"content"    ` // 审批备注
	IsRead     int         `json:"isRead"     ` // 是否已读 0未读 1已读
}
