// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// BotDataSet is the golang structure for table chat.
type BotDataSet struct {
	Id         uint        `json:"id" dc:"ID"         ` // ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 删除时间
	BotId       uint        `json:"botId" dc:"机器人Id"      ` // 机器人Id
	DataSetId uint        `json:"dataSetId" dc:"数据集Id"      ` // 数据集Id
}

func (df *BotDataSet) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *BotDataSet) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}