// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BotUserFile is the golang structure for table botUserFile.
type BotUserFile struct {
	Id         uint        `json:"id"         ` // 流程ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 删除时间
	BotId      int         `json:"botId"      ` // 机器人ID
	FileId     int         `json:"fileId"     ` // 文件ID
}
