// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// botFolder is the golang structure for table botFolder.
type BotFolder struct {
	Id                uint        `json:"id"                ` //
	CreateTime        *gtime.Time `json:"createTime"        ` // 创建时间
	UpdateTime        *gtime.Time `json:"updateTime"        ` // 更新时间
	DeleteTime        *gtime.Time `json:"deleteTime"        ` // 删除时间
	BotId             int         `json:"botId"             ` // 机器人ID
	FolderId int         `json:"folderId" ` // 文件夹ID
}
