// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplateInfo is the golang structure for table chainTemplateInfo.
type ChainTemplateInfo struct {
	Id                      uint        `json:"id"                      ` // 模版ID
	CreateTime              *gtime.Time `json:"createTime"              ` // 创建时间
	UpdateTime              *gtime.Time `json:"updateTime"              ` // 更新时间
	DeleteTime              *gtime.Time `json:"deleteTime"              ` // 删除时间
	UserId                  int         `json:"userId"                  ` // 用户ID
	ChainTemplateName       string      `json:"chainTemplateName"       ` // 模版名称
	FatherId                int         `json:"fatherId"                ` // 父ID
	Version                 string      `json:"version"                 ` // 版本号
	VersionDesc             string      `json:"versionDesc"             ` // 版本描述
	Desc                    string      `json:"desc"                    ` // 描述
	Icon                    string      `json:"icon"                    ` // icon图
	DownloadCount           int         `json:"downloadCount"           ` // 下载次数
	ChainLevel              int         `json:"chainLevel"              ` // 层级
	ChainTemplateInfoStatus string      `json:"chainTemplateInfoStatus" ` // 上架下架状态 1：上架 2:下架
	BotId                   int         `json:"botId"                   ` // 如果当前版本上架，则对应当前版本的sysbot的id
	TemplateId              int         `json:"templateId"              ` // 关联的模版id
}
