// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplate is the golang structure for table chainTemplate.
type ChainTemplate struct {
	Id                  uint        `json:"id"                  ` // 模版ID
	CreateTime          *gtime.Time `json:"createTime"          ` // 创建时间
	UpdateTime          *gtime.Time `json:"updateTime"          ` // 更新时间
	DeleteTime          *gtime.Time `json:"deleteTime"          ` // 删除时间
	UserId              int         `json:"userId"              ` // 用户ID
	ChainTemplateName   string      `json:"chainTemplateName"   ` // 模版名称
	Nodes               []map[string]interface{}      `json:"nodes"               ` // 节点数据
	Edges               []map[string]interface{}      `json:"edges"               ` // 边缘数据
	FatherId            int         `json:"fatherId"            ` // 父ID
	Version             string      `json:"version"             ` // 版本号
	VersionDesc         string      `json:"versionDesc"         ` // 版本描述
	Desc                string      `json:"desc"                ` // 描述
	Icon                string      `json:"icon"                ` // icon图
	ChainLevel          int         `json:"chainLevel"          ` // 层级
	ApproveStatus       string      `json:"approveStatus"       ` // 审批状态  1：待审批 2:已通过 3:已驳回
	ChainTemplateStatus string      `json:"chainTemplateStatus" ` // 上架下架状态 1：上架 2:下架
	BotId               int         `json:"botId"               ` // 如果当前版本上架，则对应当前版本的sysbot的id
	UseKnowledge        int         `json:"useKnowledge"        ` // 是否使用知识库
}
