// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BotUserFile is the golang structure for table botUserFile.
type ChainBotUserRelation struct {
	Id         uint        `json:"id"         ` // 流程ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 删除时间
	RelationId      int         `json:"relationId"      ` // 关系ID
	RelationType     string         `json:"relationType"     ` // 关系类型
	UserPermission     string         `json:"userPermission"     ` // 用户权限
	UserId     int         `json:"userId"     ` // 用户ID

}
