// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ChainTemplateScene is the golang structure for table chainTemplateScene.
type ChainTemplateScene struct {
	Id              uint        `json:"id"              ` // ID
	CreateTime      *gtime.Time `json:"createTime"      ` // 创建时间
	UpdateTime      *gtime.Time `json:"updateTime"      ` // 更新时间
	DeleteTime      *gtime.Time `json:"deleteTime"      ` // 删除时间
	ChainTemplateId int         `json:"chainTemplateId" ` // chainID
	SceneId         int         `json:"sceneId"         ` // 场景id
}
