// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
	"time"
)
var nilTime time.Time
// Chat is the golang structure for table chat.
type Chat struct {
	Id          uint        `json:"id" dc:"聊天ID"         ` // 聊天ID
	CreateTime  *gtime.Time `json:"createTime" dc:"创建时间" ` // 创建时间
	UpdateTime  *gtime.Time `json:"updateTime" dc:"更新时间" ` // 更新时间
	DeleteTime  *gtime.Time `json:"deleteTime" dc:"删除时间" ` // 删除时间
	ChatName    string      `json:"chatName" dc:"对话名称"      ` // 对话名称
	Type        string      `json:"type" dc:"对话类型"      ` // 对话类型
	UserId      uint        `json:"userId" dc:"用户ID"    ` // 用户ID
	ContextType string      `json:"contextType" dc:"上下文类型"` //上下文类型
	IsTemp      int         `json:"istemp" dc:"是否是临时会话 0:否 1:是"`
}

func (df *Chat) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *Chat) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}