// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompareRecord is the golang structure for table compareRecord.
type CompareRecord struct {
	Id              uint         `json:"id" dc:"记录ID"             ` // 记录ID
	CreateTime      *gtime.Time `json:"createTime" dc:"创建时间"     ` // 创建时间
	UpdateTime      *gtime.Time `json:"updateTime"  dc:"更新时间"    ` // 更新时间
	DeleteTime      *gtime.Time `json:"deleteTime"  dc:"删除时间"    ` // 删除时间
	ParentId        uint         `json:"parentId"  dc:"父记录ID"      ` // 父记录ID
	SourceMessageId uint         `json:"sourceMessageId" dc:"源消息ID" ` // 源消息ID
	TargetMessageId uint         `json:"targetMessageId" dc:"目标消息ID" ` // 目标消息ID
	Result          string      `json:"result"  dc:"比较结果"        ` // 比较结果
}


func (df *CompareRecord) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *CompareRecord) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}