// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type File struct {
	Id           uint        `json:"id"           ` //
	CreateTime   *gtime.Time `json:"createTime"   ` // 创建时间
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 更新时间
	DeleteTime   *gtime.Time `json:"deleteTime"   ` // 删除时间
	Url          string      `json:"url"          ` // 文件地址
	FileName     string      `json:"fileName"     ` // 文件名
	ParseStatus  string      `json:"parseStatus"  ` // 解析状态 1：Parsing  2:Success 3:Failure
	Md5          string      `json:"md5"          ` // 文件的md5值
	Size         int         `json:"size"         ` // 文件大小，单位kb
}

type FileRes struct {
	File *File `json:"file"`
	UserInfo        *UserRes             `json:"userInfo"`
}

func (df *File) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *File) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}