// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// Folder is the golang structure for table folder.
type Folder struct {
	Id         uint        `json:"id" dc:"模型ID"         ` // 模型ID
	CreateTime *gtime.Time `json:"createTime" dc:"创建时间" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" dc:"更新时间" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" dc:"删除时间" ` // 删除时间
	FolderName       string      `json:"folderName" dc:"资源名称"      ` // 资源名称
	UserId int         `json:"userId" ` //
}

type FolderRes struct {
	Folder *Folder `json:"folder"`
	UserInfo        *UserRes        `json:"userInfo"`
}

func (df *Folder) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *Folder) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}