// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// FolderDataSet is the golang structure for table chat.
type FolderDataSet struct {
	Id         uint        `json:"id" dc:"ID"         ` // ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 删除时间
	DataSetId       uint    `json:"dataSetId" dc:"数据集Id"      ` // 数据集Id
	SetFolderId uint        `json:"setFolderId" dc:"文件夹Id"      ` // 文件夹Id
}

func (df *FolderDataSet) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *FolderDataSet) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}