// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type MemberToken struct {
	Id           uint        `json:"id"           ` //
	CreateTime   *gtime.Time `json:"createTime"   ` // 创建时间
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 更新时间
	DeleteTime   *gtime.Time `json:"deleteTime"   ` // 删除时间
	UserId 	 int         `json:"userId"       ` // 用户ID
	TokenTotal int `json:"tokenTotal" ` // token总数
	TokenUse int `json:"tokenUse" ` // token使用数
}


func (df *MemberToken) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *MemberToken) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}