// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MessageModelUsageTokens is the golang structure for table ,messageModelUsageTokens.
type MessageModelUsageTokens struct {
	Id          uint         `json:"id" dc:"消息ID"         ` // 消息ID
	CreateTime  *gtime.Time `json:"createTime" dc:"创建时间"  ` // 创建时间
	UpdateTime  *gtime.Time `json:"updateTime" dc:"更新时间"  ` // 更新时间
	DeleteTime  *gtime.Time `json:"deleteTime" dc:"删除时间"  ` // 删除时间
	MessageId   uint        `json:"messageId"  dc:"消息Id"   ` // 所属消息ID
	ModelId     uint 	    `json:"modelId" dc:"模型Id" ` 	   //所属模型ID
	UsageTotalTokens      uint        `json:"usageTotalTokens"`  //当前messsage的token使用总量
	OriginalToken 	 uint        `json:"originalToken"`   //当前messsage的token计算总量
}

func (df *MessageModelUsageTokens) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *MessageModelUsageTokens) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}