// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Payment is the golang structure for table payment.
type Payment struct {
	Id            uint        `json:"id"            dc:"支付记录ID"` // 支付记录ID
	CreateTime    *gtime.Time `json:"createTime"    dc:"创建时间"` // 创建时间
	UpdateTime    *gtime.Time `json:"updateTime"    dc:"更新时间"` // 更新时间
	DeleteTime    *gtime.Time `json:"deleteTime"    dc:"删除时间"` // 删除时间
	MethodType    string      `json:"methodType"    dc:"支付方式"` // 支付方式
	Amount        float64     `json:"amount"        dc:"支付金额"` // 支付金额
	Status        string      `json:"status"        dc:"支付状态"` // 支付状态
	PaymentTime   *gtime.Time `json:"paymentTime"   dc:"付款时间"` // 付款时间
	OrderId       uint        `json:"orderId"       dc:"订单ID"` // 订单ID
	TransactionId string      `json:"transactionId" dc:"交易号"` // 交易号
}

func (df *Payment) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *Payment) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}