// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id          uint        `json:"id"  dc:"商品ID"          ` // 商品ID
	CreateTime  *gtime.Time `json:"createTime" dc:"创建时间"   ` // 创建时间
	UpdateTime  *gtime.Time `json:"updateTime" dc:"更新时间"   ` // 更新时间
	DeleteTime  *gtime.Time `json:"deleteTime" dc:"删除时间"` // 删除时间
	Name        string      `json:"name"       dc:"商品名称" ` // 商品名称
	Description string      `json:"description" dc:"商品描述"` // 商品描述
	Price       float64     `json:"price"      dc:"商品价格" ` // 商品价格
	Duration    uint64      `json:"duration"   dc:"使用时长（单位：豪秒）" ` // 使用时长（单位：豪秒）
	Status      string      `json:"status"    dc:"商品状态 1、下架 2、上架"  ` // 商品状态
	OriginalPrice float64  `json:"originalPrice"   dc:"原价格"   ` // 原价格
	DurationType string `json:"durationType" dc:"使用时长类型  1、month:月;2、year:年;3、custom:自定义"`
	TokenLimit int `json:"tokenLimit" dc:"token限额"`
}

func (df *Product) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *Product) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}