// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// ApiKey is the golang structure for table chat.
type PromptChainLog struct {
	Id         uint        `json:"id" dc:"ID"         ` // ID
	Created_at *gtime.Time `json:"created_at" dc:"创建时间" ` // 创建时间
	Update_at *gtime.Time `json:"update_at" dc:"更新时间" ` // 更新时间
	Uuid string `json:"uuid" dc:"uuid" ` // uuid
	TraceId string `json:"traceId" dc:"traceId" ` // trace_id
	ExecutionTime string `json:"execution_time" dc:"execution_time" ` // execution_time
	TokenConsumed map[string]interface{}  `json:"token_consumed" dc:"token_consumed" ` // token_consumed
	Results [] map[string]interface{}  `json:"results" dc:"results" ` // result
	ChainId string `json:"chainId" dc:"chainId" ` // chain_id
	MessageId string `json:"messageId" dc:"messageId" ` // message_id
}

func (df *PromptChainLog) DefaultUpdateTime() {
	df.Update_at = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *PromptChainLog) DefaultCreateTime() {
	df.Created_at = gtime.Now()
}