// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// SetFolder is the golang structure for table chat.
type SetFolder struct {
	Id         uint        `json:"id" dc:"ID"         ` // ID
	CreateTime *gtime.Time `json:"createTime" dc:"创建时间" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" dc:"更新时间" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" dc:"删除时间" ` // 删除时间
	SetFolderName       string        `json:"setFolderName" dc:"文件夹名称"      ` // 文件夹名称
	UserId uint        `json:"userId" dc:"用户ID"      ` // 用户ID
	EmbeddingModel string        `json:"embeddingModel" dc:"嵌入模型"      ` // 嵌入模型
}

func (df *SetFolder) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *SetFolder) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}