// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)
// SysConfig is the golang structure for table SysConfig.
type SysConfig struct {
	Id         uint        `json:"id" dc:"ID"         ` // ID
	Created_at *gtime.Time `json:"createTime" dc:"创建时间" ` // 创建时间
	Updated_at *gtime.Time `json:"updateTime" dc:"更新时间" ` // 更新时间
	Config_name		string     `json:"config_name" dc:"名称"` // 名称
	Config_key		string     `json:"config_key" dc:"唯一标识"` // 唯一标识
	Config_value 	 string     `json:"config_value" dc:"配置"` // 配置
	Config_type 	 string     `json:"config_type" dc:"类型"` // 类型
	Remark 	 string     `json:"remark" dc:"备注"` //
}

func (df *SysConfig) DefaultUpdateTime() {
	df.Updated_at = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *SysConfig) DefaultCreateTime() {
	df.Created_at = gtime.Now()
}