// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TokenUsageLimit is the golang structure for table TokenUsageLimit.
type TokenUsageLimit struct {
	Id         uint        `json:"id"         ` // 验证码ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 更新时间
	UserId	 	uint        `json:"userId"     ` // 用户ID
	DailyTokens	uint 	   `json:"dailyTokens" ` // 每日可用次数
}

func (df *TokenUsageLimit) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *TokenUsageLimit) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}