// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserFile is the golang structure for table userFile.
type UserFile struct {
	Id           uint        `json:"id"           ` //
	CreateTime   *gtime.Time `json:"createTime"   ` // 创建时间
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 更新时间
	DeleteTime   *gtime.Time `json:"deleteTime"   ` // 删除时间
	FileName         string      `json:"fileName"         ` // 文件名
	UserId 		 int 		 `json:"userId" ` //用户Id
	FileId         int `json:"fileId" ` // 文件资源ID
	FileType 	   string `json:"fileType" ` // 文件类型
}

type UserFileInfo struct {
	ParseStatus  string      `json:"parseStatus"`
	Url 		string        `json:"url"`
	*UserFile
}

type UserFileRes struct {
	File  *UserFileInfo 	  `json:"file"`
	UserInfo         *UserRes             `json:"userInfo"`
	FolderName string `json:"folderName"`
}
type UserFileResInfo struct {
	IsParse          bool                `json:"isParse"`
	Url 			string        		 `json:"url"`
	ParseStatus 	string     			 `json:"parseStatus"`
	*UserFile
}


func (df *UserFile) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *UserFile) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}