// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VerificationCode is the golang structure for table verificationCode.
type VerificationCode struct {
	Id         uint        `json:"id"         ` // 验证码ID
	CreateTime *gtime.Time `json:"createTime" ` // 创建时间
	UpdateTime *gtime.Time `json:"updateTime" ` // 更新时间
	DeleteTime *gtime.Time `json:"deleteTime" ` // 更新时间
	Phone      string      `json:"phone"      ` // 手机号码
	Code       string      `json:"code"       ` // 验证码
	ExpireTime *gtime.Time `json:"expireTime" ` // 过期时间
	IsVerified int         `json:"isVerified" ` // 是否已验证
}

func (df *VerificationCode) DefaultUpdateTime() {
	df.UpdateTime = gtime.Now()
}

// DefaultCreateAt changes the default createAt field
func (df *VerificationCode) DefaultCreateTime() {
	df.CreateTime = gtime.Now()
}